export const doorData = [
    { number: '2', img: 'https://i.imgur.com/vWVhicm.png', text: '"Happy Holidays, Team! Thanks for another great year together :) Can’t wait to tackle 2022 with you all. Much love!"', name: '- JDB' },
    { number: '5', img: 'https://imgur.com/F5bEjR0.png', text: '“Merry Christmas! Woo-hoo!! Where them doughnuts?!”', name: '- Bryce'},
    { number: '1', img: 'https://i.imgur.com/sKMijDj.jpg', text: ' "We woof you a merry holidays!"', name: '- Poppy and Chip' },
    { number: '7', img: 'https://i.imgur.com/CUK7RHJ.png', text: '"Goodbyes are never easy, we said farewell to an amazing colleague and friend.', name:'- Fiona W' },
    { number: '17', img: 'https://monkeypuzzlemuswellhill.co.uk/wp-content/uploads/2017/08/coming-soon.jpg', text: '"Check back later"', name:'- TBC' },
    { number: '8', img: 'https://i.imgur.com/cRu9AKN.png', text: '"Who wore it best?"', name:'- Stripe edition' },
    { number: '13', img: 'https://i.imgur.com/fuGaZZA.png', text: '"Spoooooky season, Haloween 2021 and the team brought the looks..."', name:'- GA Halloween' },
    { number: '10', img: 'https://i.imgur.com/B1dBKHF.jpg', text: '"Hug your homies in 2022"', name:'- Nat and Ellen' },
    { number: '3', img: 'https://i.imgur.com/FkZFisb.jpg', text: '"Our latest team member arrived in January 2021."', name: '- Astrid and Leo' },
    { number: '11', img: 'https://i.imgur.com/IzeaGxJ.png', text: '"Who wore it best?"', name:'- Delivery Team' },
    { number: '22', img: 'https://monkeypuzzlemuswellhill.co.uk/wp-content/uploads/2017/08/coming-soon.jpg', text: '"Check back later"', name:'- TBC' },
    { number: '9', img: 'https://i.imgur.com/pepJKAs.png', text: '"“Admissions was out of this world”" ', name:'- Team admish' },
    { number: '12', img: 'https://i.imgur.com/lcdP4S1.png', text: '"So good to RECONNECT with everyone at our team on- site.  Even three of our team from Paris came over, plus some who attended virtually."', name:'- #EnterpriseEurope' },
    { number: '19', img: 'https://monkeypuzzlemuswellhill.co.uk/wp-content/uploads/2017/08/coming-soon.jpg', text: '"Check back later"', name:'- TBC' },
    { number: '14', img: 'https://i.imgur.com/TxzERWN.png', text: '"Another incredible effort made for Haloween 2021!"', name:'- UK Delivery Team' },
    { number: '24', img: 'https://monkeypuzzlemuswellhill.co.uk/wp-content/uploads/2017/08/coming-soon.jpg', text: '"Check back later"', name:'- TBC' },
    { number: '15', img: 'https://i.imgur.com/xWWBTY7.png', text: '"When you eat all your advent calendar chocolate in one go..."', name:'- Gabe and Gayle' },
    { number: '4', img: 'https://i.imgur.com/czDaOuY.jpg', text: '"Stay woke"', name: '- Gabe and Gayle' },
    { number: '16', img: 'https://i.imgur.com/Qplmp1P.png', text: '"Its been a difficult couple of years but I feel so much gratitude to work with all of you!"', name:'- Anna' },
    { number: '20', img: 'https://monkeypuzzlemuswellhill.co.uk/wp-content/uploads/2017/08/coming-soon.jpg', text: '"Check back later"', name:'- TBC' },
    { number: '18', img: 'https://monkeypuzzlemuswellhill.co.uk/wp-content/uploads/2017/08/coming-soon.jpg', text: '"Check back later"', name:'- TBC' },
    { number: '6', img: 'https://i.imgur.com/pxR6jVr.jpg', text: '"Who can forget Caseys strangest item in her house?"', name:'- Casey and the painting' },
    { number: '21', img: 'https://monkeypuzzlemuswellhill.co.uk/wp-content/uploads/2017/08/coming-soon.jpg', text: '"Check back later"', name:'- TBC' },
    { number: '23', img: 'https://monkeypuzzlemuswellhill.co.uk/wp-content/uploads/2017/08/coming-soon.jpg', text: '"Check back later"', name:'- TBC' },
  ]