export const doorData = [
    { number: '2', img: './Images/SP.png', text: '"Ahoy there everyone! A highlight for me was FL Appreciation Week and obviously being Ned for a day!"', name: '- Somerset' },
    { number: '5', img: './Images/JF.png', text: '“Im a survivor, Im not gonna give up, Im not gonna stop, Im gonna work harder, Im a survivor, Im gonna make it, I will survive, keep on surviving”', name: '- John'},
    { number: '1', img: './Images/MB.png', text: ' "Calm is a superpower"', name: '- Michelle' },
    { number: '7', img: './Images/EM.png', text: '"Dont forget to believe in a little magic!"', name:'- Ellen' },
    { number: '17', img: './Images/ABB.png', text: '"Have a dance to this today!"', link: 'https://www.youtube.com/watch?v=jj-oTtHTwVY', name:'- Astrid' },
    { number: '8', img: './Images/FW.png', text: '"Vintage is just overpriced retro" - Somerset Prew (in reference to how to refer to Brexit) ', name:'- Fi' },
    { number: '13', img: './Images/MIN.png', text: '"What do you see? Glass is either half full or half empty.. Either way Im still gonna have another round.".. Merry Christmas and Happy New Year.. see you in 2021!', name:'- Mina' },
    { number: '10', img: './Images/NH.png', text: '"The secret of change is to focus all of your energy, not on fighting the old, but on building the new." - Socrates', name:'- Nat' },
    { number: '3', img: './Images/DC.png', text: '"Does work always have to be serious? Neigh. These two amazing people surprised me, yelled "haaaaaaay" and it made my day. As they say, you can take a horse to water, but you cant make it call you on Zoom."', name: '- Callum ' },
    { number: '11', img: './Images/AI.png', text: '"Shout out to Antonios MO!"', name:'- Chip' },
    { number: '22', img: './Images/AK.png', text: 'I love that GA is full of "do-ers" who arent afraid to take risk. Ive learned a lot from this team because I know they are all trying too, instead of sitting at the sidelines. Quote by Brene Brown', name:'- Anna' },
    { number: '9', img: './Images/CM.gif', text: '"“Please enjoy this festive-based metaphor for everyone clinging on to their sanity in 2020. As Tiny Tim said “God bless us everyone”" ', name:'- Ciaran' },
    { number: '12', img: './Images/MIKES.png', text: '"When Triplet Mike kept crashing our Zoom meeting"', name:'- Kremmy' },
    { number: '19', img: './Images/SOM.png', text: '"Who wore it best?"', name:'- you decide' },
    { number: '14', img: './Images/ECS.png', text: '"If 2020 has taught me anything its that "The problem is not the problem. The problem is your attitude about the problem." - Jack Sparrow (Pirates of the Caribbean)', name:'- Edward' },
    { number: '24', img: './Images/JDBS.png', text: '"If the 21st century was a TV show, 2020 would likely be the worst (and most over-the-top) episode. And yet - look at the cast! STELLAR. Thank you everyone for making 2020 a little less crazy and a lot more positive than it could have been. So very grateful for each and every one of you, for your empathy, care, support and friendship. Big virtual hug!"', name:'- JDB' },
    { number: '15', img: './Images/GH.png', text: '“When you want to hide until 2020 is over” (or the teacher comes around and you are shy.) Happy Holidays to all Mums work friends!', name:'- Gabe (and Gayle)' },
    { number: '4', img: './Images/CAL.png', text: '"The debut of the Caltato"', name: '- Kremmy' },
    { number: '16', img: './Images/CHED.jpg', text: '"Have yourself a Meow-y little Christmas!"', name:'- Cheddar' },
    { number: '20', img: './Images/BT.png', text: '"Again...Who wore it best though?"', name:'- you must decide' },
    { number: '18', img: './Images/AR.png', text: '"The time in team breakfast when John Furno told us how much he enjoyed watching "The Fall" 😂🤪"', name:'- Adam' },
    { number: '6', img: './Images/YA.png', text: '"Business as usual!"', name:'- Antonio' },
    { number: '21', img: './Images/GREY.png', text: '"Cmon now...Who REALLY wore it best?"', name:'- too hard to decide' },
    { number: '23', img: './Images/JDB.png', text: '"Who likes to party?"', name:'- This guy' },
  ]